services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fantasy_products
      MYSQL_USER: myuser
      MYSQL_PASSWORD: Bootcamp!
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - mysql-db-network
    restart: always

networks:
  mysql-db-network:
    driver: bridge